name: Deploy boomchain-token-claimer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your.production.url

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes Cluster
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f ./k8s/deployment.yaml
          kubectl rollout status deployment/boomchain-token-claimer
